apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: iheatk3tk-python 
  janus-idp.io/tekton: iheatk3tk-python
  backstage.io/kubernetes-id: iheatk3tk-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iheatk3tk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml