apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: iheatk3tk-python-gitops
  description: This is GitOps manifest for iheatk3tk-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=iheatk3tk-python
    backstage.io/kubernetes-id: iheatk3tk-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: iheatk3tk-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:iheatk3tk-python
