apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iheatk3tk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iheatk3tk-python 
  name: iheatk3tk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iheatk3tk-python 
